language: python
notifications:
  email:
    - paul4hough@gmail.com

before_script:
  - echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script: "bundle exec rake -t test"
