name    'puppet-python'
version '1.0.0'
source 'https://github.com/pahoughton/puppet-python'
author 'Paul Houghton <paul4hough@gmail.com>'
license 'Apache License, Version 2.0'
summary 'Provides Python and Python development packages'
description 'Provides Python 2.7 and 3.n development packages'
project_page 'https://github.com/pahoughton/puppet-python'
